# Stage 1: Build the application
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package.json package-lock.json* ./

# Install dependencies and build the application for staging
RUN npm install --no-optional && npm run build:dev

# Stage 2: Serve the application with a lightweight web server
FROM nginx:alpine

# Copy the build artifacts from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose the port the nginx server will run on
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]