import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, AlertCircle } from "lucide-react";
import { getUtilityVendDetails } from '@/services/api';
import { UtilityVend } from '@/types/dashboard';
import { useOrganization } from '@/context/useOrganization';

interface VendingDetailsModalProps {
  vendUuid: string;
  isOpen: boolean;
  onClose: () => void;
}

export const VendingDetailsModal = ({ vendUuid, isOpen, onClose }: VendingDetailsModalProps) => {
  const { selectedOrganization } = useOrganization();
  const [vendDetails, setVendDetails] = useState<UtilityVend | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen && vendUuid && selectedOrganization) {
      const fetchDetails = async () => {
        setIsLoading(true);
        setError(null);
        try {
          const data = await getUtilityVendDetails(selectedOrganization.uuid, vendUuid);
          setVendDetails(data);
        } catch (err) {
          setError('Failed to fetch vend details.');
          console.error(err);
        } finally {
          setIsLoading(false);
        }
      };
      fetchDetails();
    }
  }, [isOpen, vendUuid, selectedOrganization]);

  const renderDetailRow = (label: string, value: React.ReactNode) => (
    <div className="grid grid-cols-3 gap-4 py-2 border-b">
      <dt className="text-sm font-medium text-muted-foreground">{label}</dt>
      <dd className="col-span-2 text-sm">{value}</dd>
    </div>
  );

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[525px]">
        <DialogHeader>
          <DialogTitle>Transaction Details</DialogTitle>
          <DialogDescription>
            Detailed information for vend reference: {vendDetails?.vend_reference || '...'}
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {isLoading && (
            <div className="flex justify-center items-center h-40">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          )}
          {error && !isLoading && (
            <div className="flex flex-col justify-center items-center h-40 text-red-500">
              <AlertCircle className="h-8 w-8 mb-2" />
              <p>{error}</p>
            </div>
          )}
          {vendDetails && !isLoading && !error && (
            <dl>
              {renderDetailRow('Status', <Badge variant={vendDetails.status === 'successful' ? 'success' : 'destructive'}>{vendDetails.status}</Badge>)}
              {renderDetailRow('Meter Number', vendDetails.meter_number)}
              {renderDetailRow('Amount', `₦${parseFloat(vendDetails.amount).toLocaleString()}`)}
              {vendDetails.token_type === 'mgtk' && renderDetailRow('Operation', <Badge variant="outline">{vendDetails.token_class || 'N/A'}</Badge>)}
              {vendDetails.token_type === 'mgtk' && renderDetailRow('Action', <Badge variant="outline">{vendDetails.token_sub_class || 'N/A'}</Badge>)}
              {renderDetailRow('Date/Time', new Date(vendDetails.created).toLocaleString())}
              {renderDetailRow('Generated By', vendDetails.initiated_by)}
              {renderDetailRow('Token Type', <Badge>{vendDetails.token_type?.toUpperCase()}</Badge>)}
              {renderDetailRow('Tokens', (
                <div className="flex flex-col gap-2">
                  {vendDetails.token.map((t, index) => (
                    <Badge key={index} variant="outline" className="font-mono text-xs">
                      {t}
                    </Badge>
                  ))}
                </div>
              ))}
              {renderDetailRow('Transaction Ref', vendDetails.transaction)}
              {renderDetailRow('Organization', vendDetails.organization)}
            </dl>
          )}
        </div>
        <DialogFooter>
          <Button onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};